name: appnotes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_quill: ^10.8.5
  image_picker: ^0.8.9
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  device_info_plus: ^11.4.0 # ✅ Versión compatible con Android Gradle Plugin 8+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # ✅ Versión compatible con SDK 3.7+

flutter:
  uses-material-design: true

  assets:
    - assets/images/
